export const template = {
	speed: 3,
	fm1_listener: 0,
	fm2_listener: 0,
	perc_listener: 0,
	a_mode: 0,
	b_mode: 0,
	c_mode: 0,
	a_steps_0: 5,
	a_steps_1: 2,
	a_steps_2: 3,
	b_steps_0: 4,
	b_steps_1: 4,
	b_steps_2: 4,
	c_steps_0: 2,
	c_steps_1: 4,
	c_steps_2: 8,
	fm1_freq_preset: 0,
	fm1_mod_preset: 0,
	fm1_shape_preset: 0,
	fm2_freq_preset: 0,
	fm2_mod_preset: 0,
	fm2_shape_preset: 0,
	perc_sound_preset: 0,
	perc_transpose_preset: 0,
	perc_shape_preset: 0,
}